package edu.gatech.omscs.dscars.model;
// default package
// Generated Mar 28, 2015 1:24:52 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CoreEngine generated by hbm2java
 */
@Entity
@Table(name = "CoreEngine", catalog = "DSCARS")
public class CoreEngine implements java.io.Serializable {

	private Integer settingsId;
	private User user;
	private int maxClassSizeDefault;
	private int studentsPerInstructor;
	private boolean isShadow;

	public CoreEngine() {
	}

	public CoreEngine(User user, int maxClassSizeDefault,
			int studentsPerInstructor, boolean isShadow) {
		this.user = user;
		this.maxClassSizeDefault = maxClassSizeDefault;
		this.studentsPerInstructor = studentsPerInstructor;
		this.isShadow = isShadow;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SettingsID", unique = true, nullable = false)
	public Integer getSettingsId() {
		return this.settingsId;
	}

	public void setSettingsId(Integer settingsId) {
		this.settingsId = settingsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "MaxClassSizeDefault", nullable = false)
	public int getMaxClassSizeDefault() {
		return this.maxClassSizeDefault;
	}

	public void setMaxClassSizeDefault(int maxClassSizeDefault) {
		this.maxClassSizeDefault = maxClassSizeDefault;
	}

	@Column(name = "StudentsPerInstructor", nullable = false)
	public int getStudentsPerInstructor() {
		return this.studentsPerInstructor;
	}

	public void setStudentsPerInstructor(int studentsPerInstructor) {
		this.studentsPerInstructor = studentsPerInstructor;
	}

	@Column(name = "IsShadow", nullable = false)
	public boolean isIsShadow() {
		return this.isShadow;
	}

	public void setIsShadow(boolean isShadow) {
		this.isShadow = isShadow;
	}

}
