package edu.gatech.omscs.dscars.model;
// default package
// Generated Mar 27, 2015 4:54:21 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Instructor generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Instructor", catalog = "DSCARS")
public class Instructor implements java.io.Serializable {

	private int instructorId;
	private String name;
	private boolean isProfessor;
	private boolean active;
	private byte currentCourseCount;
	private Set<CourseCompetency> courseCompetencies = new HashSet<CourseCompetency>(
			0);
	private Set<RecommendedSection> recommendedSections = new HashSet<RecommendedSection>(
			0);
	private Set<Course> courses = new HashSet<Course>(0);
	private Set<RecommendedTas> recommendedTases = new HashSet<RecommendedTas>(
			0);
	private Set<StudentCourseHistory> studentCourseHistories = new HashSet<StudentCourseHistory>(
			0);
	private Set<Section> sections = new HashSet<Section>(0);

	public Instructor() {
	}

	public Instructor(int instructorId, String name, boolean isProfessor,
			boolean active, byte currentCourseCount) {
		this.instructorId = instructorId;
		this.name = name;
		this.isProfessor = isProfessor;
		this.active = active;
		this.currentCourseCount = currentCourseCount;
	}

	public Instructor(int instructorId, String name, boolean isProfessor,
			boolean active, byte currentCourseCount,
			Set<CourseCompetency> courseCompetencies,
			Set<RecommendedSection> recommendedSections, Set<Course> courses,
			Set<RecommendedTas> recommendedTases,
			Set<StudentCourseHistory> studentCourseHistories,
			Set<Section> sections) {
		this.instructorId = instructorId;
		this.name = name;
		this.isProfessor = isProfessor;
		this.active = active;
		this.currentCourseCount = currentCourseCount;
		this.courseCompetencies = courseCompetencies;
		this.recommendedSections = recommendedSections;
		this.courses = courses;
		this.recommendedTases = recommendedTases;
		this.studentCourseHistories = studentCourseHistories;
		this.sections = sections;
	}

	@Id
	@Column(name = "instructorId", unique = true, nullable = false)
	public int getInstructorId() {
		return this.instructorId;
	}

	public void setInstructorId(int instructorId) {
		this.instructorId = instructorId;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "isProfessor")
	public boolean isIsProfessor() {
		return this.isProfessor;
	}

	public void setIsProfessor(boolean isProfessor) {
		this.isProfessor = isProfessor;
	}

	@Column(name = "active")
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "currentCourseCount")
	public byte getCurrentCourseCount() {
		return this.currentCourseCount;
	}

	public void setCurrentCourseCount(byte currentCourseCount) {
		this.currentCourseCount = currentCourseCount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instructor")
	public Set<CourseCompetency> getCourseCompetencies() {
		return this.courseCompetencies;
	}

	public void setCourseCompetencies(Set<CourseCompetency> courseCompetencies) {
		this.courseCompetencies = courseCompetencies;
	}

	
}
