package edu.gatech.omscs.dscars.model;
// default package
// Generated Mar 28, 2015 1:24:52 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PchSub generated by hbm2java
 */
@Entity
@Table(name = "PCH_Sub", catalog = "DSCARS")
public class PchSub implements java.io.Serializable {

	private Integer pchSubId;
	private Course course;
	private PreferredCourseHistory preferredCourseHistory;
	private int semesterId;
	private byte priority;

	public PchSub() {
	}

	public PchSub(Course course, PreferredCourseHistory preferredCourseHistory,
			int semesterId, byte priority) {
		this.course = course;
		this.preferredCourseHistory = preferredCourseHistory;
		this.semesterId = semesterId;
		this.priority = priority;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PCH_Sub_ID", unique = true, nullable = false)
	public Integer getPchSubId() {
		return this.pchSubId;
	}

	public void setPchSubId(Integer pchSubId) {
		this.pchSubId = pchSubId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CourseID", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PCH_ID", nullable = false)
	public PreferredCourseHistory getPreferredCourseHistory() {
		return this.preferredCourseHistory;
	}

	public void setPreferredCourseHistory(
			PreferredCourseHistory preferredCourseHistory) {
		this.preferredCourseHistory = preferredCourseHistory;
	}

	@Column(name = "SemesterID", nullable = false)
	public int getSemesterId() {
		return this.semesterId;
	}

	public void setSemesterId(int semesterId) {
		this.semesterId = semesterId;
	}

	@Column(name = "Priority", nullable = false)
	public byte getPriority() {
		return this.priority;
	}

	public void setPriority(byte priority) {
		this.priority = priority;
	}

}
