package edu.gatech.omscs.dscars.model;
// default package
// Generated Mar 28, 2015 1:24:52 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PreferredCourseHistory generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PreferredCourseHistory", catalog = "DSCARS")
public class PreferredCourseHistory implements java.io.Serializable {

	private Integer pchId;
	private Semester semester;
	private Program program;
	private Student student;
	private Contact contact;
	private int numCoursesDesired;
	private Date dateCreated;
	private Set<PchSub> pchSubs = new HashSet<PchSub>(0);

	public PreferredCourseHistory() {
	}

	public PreferredCourseHistory(int studentId, int numCoursesDesired,
			Date dateCreated) {
		student=new Student();
		student.setStudentId(studentId);
		this.numCoursesDesired = numCoursesDesired;
		this.dateCreated = dateCreated;
	}

	public PreferredCourseHistory(int studentId, int numCoursesDesired,
			Date dateCreated, Set<PchSub> pchSubs) {
		student=new Student();
		student.setStudentId(studentId);
		this.numCoursesDesired = numCoursesDesired;
		this.dateCreated = dateCreated;
		this.pchSubs = pchSubs;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SemesterID", nullable = false)
	public Semester getSemester() {
		return semester;
	}

	public void setSemester(Semester semester) {
		this.semester = semester;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "programId", nullable = false)
	public Program getProgram() {
		return program;
	}

	public void setProgram(Program program) {
		this.program = program;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PCH_ID", unique = true, nullable = false)
	public Integer getPchId() {
		return this.pchId;
	}

	public void setPchId(Integer pchId) {
		this.pchId = pchId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "StudentID", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "Num_Courses_Desired", nullable = false)
	public int getNumCoursesDesired() {
		return this.numCoursesDesired;
	}

	public void setNumCoursesDesired(int numCoursesDesired) {
		this.numCoursesDesired = numCoursesDesired;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreated", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "preferredCourseHistory" )
	@OrderBy("priority")
	public Set<PchSub> getPchSubs() {
		return this.pchSubs;
	}

	public void setPchSubs(Set<PchSub> pchSubs) {
		this.pchSubs = pchSubs;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "studentId", insertable=false,updatable=false)
	public Contact getContact() {
		return contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

}
