package edu.gatech.omscs.dscars.model;
// default package
// Generated Mar 28, 2015 1:24:52 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SectionTas generated by hbm2java
 */
@Entity
@Table(name = "SectionTAs", catalog = "DSCARS")
public class SectionTas implements java.io.Serializable {

	private Integer staId;
	private int sectionId;
	private int instructorId;

	public SectionTas() {
	}

	public SectionTas(int sectionId, int instructorId) {
		this.sectionId = sectionId;
		this.instructorId = instructorId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "STA_ID", unique = true, nullable = false)
	public Integer getStaId() {
		return this.staId;
	}

	public void setStaId(Integer staId) {
		this.staId = staId;
	}

	@Column(name = "SectionID", nullable = false)
	public int getSectionId() {
		return this.sectionId;
	}

	public void setSectionId(int sectionId) {
		this.sectionId = sectionId;
	}

	@Column(name = "InstructorID", nullable = false)
	public int getInstructorId() {
		return this.instructorId;
	}

	public void setInstructorId(int instructorId) {
		this.instructorId = instructorId;
	}

}
