package edu.gatech.omscs.dscars.model;
// default package
// Generated Mar 28, 2015 1:24:52 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Semester generated by hbm2java
 */
@Entity
@Table(name = "Semester", catalog = "DSCARS")
public class Semester implements java.io.Serializable {

	private int semesterId;
	private Integer year;
	private Integer term;
	private String termName;
	private Set<RecommendedSection> recommendedSections = new HashSet<RecommendedSection>(
			0);
	private Set<StudentCourseHistory> studentCourseHistories = new HashSet<StudentCourseHistory>(
			0);

	public Semester() {
	}

	public Semester(int semesterId) {
		this.semesterId = semesterId;
	}

	public Semester(int semesterId, Integer year, Integer term,
			String termName, Set<RecommendedSection> recommendedSections,
			Set<StudentCourseHistory> studentCourseHistories) {
		this.semesterId = semesterId;
		this.year = year;
		this.term = term;
		this.termName = termName;
		this.recommendedSections = recommendedSections;
		this.studentCourseHistories = studentCourseHistories;
	}

	@Id
	@Column(name = "SemesterID", unique = true, nullable = false)
	public int getSemesterId() {
		return this.semesterId;
	}

	public void setSemesterId(int semesterId) {
		this.semesterId = semesterId;
	}

	@Column(name = "Year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "Term")
	public Integer getTerm() {
		return this.term;
	}

	public void setTerm(Integer term) {
		this.term = term;
	}

	@Column(name = "TermName", length = 65535)
	public String getTermName() {
		return this.termName;
	}

	public void setTermName(String termName) {
		this.termName = termName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semester")
	public Set<RecommendedSection> getRecommendedSections() {
		return this.recommendedSections;
	}

	public void setRecommendedSections(
			Set<RecommendedSection> recommendedSections) {
		this.recommendedSections = recommendedSections;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semester")
	public Set<StudentCourseHistory> getStudentCourseHistories() {
		return this.studentCourseHistories;
	}

	public void setStudentCourseHistories(
			Set<StudentCourseHistory> studentCourseHistories) {
		this.studentCourseHistories = studentCourseHistories;
	}

}
