package edu.gatech.omscs.dscars.model;
// default package
// Generated Mar 28, 2015 1:24:52 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Student", catalog = "DSCARS")
public class Student implements java.io.Serializable {

	private int studentId;
	private String name="DO NOT NEED NAME IN THIS TABLE";
	private int maxCoursesPerTerm;
	private Set<RecommendedStudents> recommendedStudentses = new HashSet<RecommendedStudents>(
			0);
	private Set<StudentCourseHistory> studentCourseHistories = new HashSet<StudentCourseHistory>(
			0);

	public Student() {
	}

	public Student(int studentId, int maxCoursesPerTerm) {
		this.studentId = studentId;
		this.maxCoursesPerTerm = maxCoursesPerTerm;
	}

	public Student(int studentId, String name, int maxCoursesPerTerm,
			Set<RecommendedStudents> recommendedStudentses,
			Set<StudentCourseHistory> studentCourseHistories) {
		this.studentId = studentId;
		this.maxCoursesPerTerm = maxCoursesPerTerm;
		this.recommendedStudentses = recommendedStudentses;
		this.studentCourseHistories = studentCourseHistories;
	}

	@Id
	@Column(name = "StudentID", unique = true, nullable = false)
	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	@Column(name = "MaxCoursesPerTerm", columnDefinition = "TINYINT", nullable = false)
	public int getMaxCoursesPerTerm() {
		return maxCoursesPerTerm;
	}

	public void setMaxCoursesPerTerm(int maxCoursesPerTerm) {
		this.maxCoursesPerTerm = maxCoursesPerTerm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<RecommendedStudents> getRecommendedStudentses() {
		return this.recommendedStudentses;
	}

	public void setRecommendedStudentses(
			Set<RecommendedStudents> recommendedStudentses) {
		this.recommendedStudentses = recommendedStudentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<StudentCourseHistory> getStudentCourseHistories() {
		return this.studentCourseHistories;
	}

	public void setStudentCourseHistories(
			Set<StudentCourseHistory> studentCourseHistories) {
		this.studentCourseHistories = studentCourseHistories;
	}

	@Column(name = "name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
