package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 27, 2015 4:54:21 PM by Hibernate Tools 4.0.0

/**
 * CoreEngine generated by hbm2java
 */
public class CoreEngine implements java.io.Serializable {

	private int settingsId;
	private User user;
	private int maxClassSizeDefault;
	private int studentsPerInstructor;
	private boolean isShadow;

	public CoreEngine() {
	}

	public CoreEngine(int settingsId, User user, int maxClassSizeDefault,
			int studentsPerInstructor, boolean isShadow) {
		this.settingsId = settingsId;
		this.user = user;
		this.maxClassSizeDefault = maxClassSizeDefault;
		this.studentsPerInstructor = studentsPerInstructor;
		this.isShadow = isShadow;
	}

	public int getSettingsId() {
		return this.settingsId;
	}

	public void setSettingsId(int settingsId) {
		this.settingsId = settingsId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getMaxClassSizeDefault() {
		return this.maxClassSizeDefault;
	}

	public void setMaxClassSizeDefault(int maxClassSizeDefault) {
		this.maxClassSizeDefault = maxClassSizeDefault;
	}

	public int getStudentsPerInstructor() {
		return this.studentsPerInstructor;
	}

	public void setStudentsPerInstructor(int studentsPerInstructor) {
		this.studentsPerInstructor = studentsPerInstructor;
	}

	public boolean isIsShadow() {
		return this.isShadow;
	}

	public void setIsShadow(boolean isShadow) {
		this.isShadow = isShadow;
	}

}
