package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 27, 2015 4:54:21 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * CourseCompetency generated by hbm2java
 */
public class CourseCompetency implements java.io.Serializable {

	private int ccId;
	private Instructor instructor;
	private Course course;
	private Date date;

	public CourseCompetency() {
	}

	public CourseCompetency(int ccId, Instructor instructor, Course course) {
		this.ccId = ccId;
		this.instructor = instructor;
		this.course = course;
	}

	public CourseCompetency(int ccId, Instructor instructor, Course course,
			Date date) {
		this.ccId = ccId;
		this.instructor = instructor;
		this.course = course;
		this.date = date;
	}

	public int getCcId() {
		return this.ccId;
	}

	public void setCcId(int ccId) {
		this.ccId = ccId;
	}

	public Instructor getInstructor() {
		return this.instructor;
	}

	public void setInstructor(Instructor instructor) {
		this.instructor = instructor;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
