package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 27, 2015 4:54:21 PM by Hibernate Tools 4.0.0

/**
 * PchSub generated by hbm2java
 */
public class PchSub implements java.io.Serializable {

	private int pchSubId;
	private Course course;
	private PreferredCourseHistory preferredCourseHistory;
	private int semesterId;
	private byte priority;

	public PchSub() {
	}

	public PchSub(int pchSubId, Course course,
			PreferredCourseHistory preferredCourseHistory, int semesterId,
			byte priority) {
		this.pchSubId = pchSubId;
		this.course = course;
		this.preferredCourseHistory = preferredCourseHistory;
		this.semesterId = semesterId;
		this.priority = priority;
	}

	public int getPchSubId() {
		return this.pchSubId;
	}

	public void setPchSubId(int pchSubId) {
		this.pchSubId = pchSubId;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public PreferredCourseHistory getPreferredCourseHistory() {
		return this.preferredCourseHistory;
	}

	public void setPreferredCourseHistory(
			PreferredCourseHistory preferredCourseHistory) {
		this.preferredCourseHistory = preferredCourseHistory;
	}

	public int getSemesterId() {
		return this.semesterId;
	}

	public void setSemesterId(int semesterId) {
		this.semesterId = semesterId;
	}

	public byte getPriority() {
		return this.priority;
	}

	public void setPriority(byte priority) {
		this.priority = priority;
	}

}
