package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 28, 2015 1:24:52 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PreferredCourseHistory generated by hbm2java
 */
@Entity
@Table(name = "PreferredCourseHistory", catalog = "DSCARS")
public class PreferredCourseHistory implements java.io.Serializable {

	private Integer pchId;
	private int studentId;
	private byte numCoursesDesired;
	private Date dateCreated;
	private Set<PchSub> pchSubs = new HashSet<PchSub>(0);

	public PreferredCourseHistory() {
	}

	public PreferredCourseHistory(int studentId, byte numCoursesDesired,
			Date dateCreated) {
		this.studentId = studentId;
		this.numCoursesDesired = numCoursesDesired;
		this.dateCreated = dateCreated;
	}

	public PreferredCourseHistory(int studentId, byte numCoursesDesired,
			Date dateCreated, Set<PchSub> pchSubs) {
		this.studentId = studentId;
		this.numCoursesDesired = numCoursesDesired;
		this.dateCreated = dateCreated;
		this.pchSubs = pchSubs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PCH_ID", unique = true, nullable = false)
	public Integer getPchId() {
		return this.pchId;
	}

	public void setPchId(Integer pchId) {
		this.pchId = pchId;
	}

	@Column(name = "StudentID", nullable = false)
	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	@Column(name = "Num_Courses_Desired", nullable = false)
	public byte getNumCoursesDesired() {
		return this.numCoursesDesired;
	}

	public void setNumCoursesDesired(byte numCoursesDesired) {
		this.numCoursesDesired = numCoursesDesired;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreated", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preferredCourseHistory")
	public Set<PchSub> getPchSubs() {
		return this.pchSubs;
	}

	public void setPchSubs(Set<PchSub> pchSubs) {
		this.pchSubs = pchSubs;
	}

}
