package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 27, 2015 4:54:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PreferredCourseHistory generated by hbm2java
 */
public class PreferredCourseHistory implements java.io.Serializable {

	private int pchId;
	private int studentId;
	private byte numCoursesDesired;
	private Date dateCreated;
	private Set<PchSub> pchSubs = new HashSet<PchSub>(0);

	public PreferredCourseHistory() {
	}

	public PreferredCourseHistory(int pchId, int studentId,
			byte numCoursesDesired, Date dateCreated) {
		this.pchId = pchId;
		this.studentId = studentId;
		this.numCoursesDesired = numCoursesDesired;
		this.dateCreated = dateCreated;
	}

	public PreferredCourseHistory(int pchId, int studentId,
			byte numCoursesDesired, Date dateCreated, Set<PchSub> pchSubs) {
		this.pchId = pchId;
		this.studentId = studentId;
		this.numCoursesDesired = numCoursesDesired;
		this.dateCreated = dateCreated;
		this.pchSubs = pchSubs;
	}

	public int getPchId() {
		return this.pchId;
	}

	public void setPchId(int pchId) {
		this.pchId = pchId;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public byte getNumCoursesDesired() {
		return this.numCoursesDesired;
	}

	public void setNumCoursesDesired(byte numCoursesDesired) {
		this.numCoursesDesired = numCoursesDesired;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Set<PchSub> getPchSubs() {
		return this.pchSubs;
	}

	public void setPchSubs(Set<PchSub> pchSubs) {
		this.pchSubs = pchSubs;
	}

}
