package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 27, 2015 4:54:21 PM by Hibernate Tools 4.0.0

/**
 * ProgramSub generated by hbm2java
 */
public class ProgramSub implements java.io.Serializable {

	private int programSubId;
	private Program program;
	private int courseId;

	public ProgramSub() {
	}

	public ProgramSub(int programSubId, Program program, int courseId) {
		this.programSubId = programSubId;
		this.program = program;
		this.courseId = courseId;
	}

	public int getProgramSubId() {
		return this.programSubId;
	}

	public void setProgramSubId(int programSubId) {
		this.programSubId = programSubId;
	}

	public Program getProgram() {
		return this.program;
	}

	public void setProgram(Program program) {
		this.program = program;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

}
