package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 27, 2015 4:54:21 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Program generated by hbm2java
 */
public class Program implements java.io.Serializable {

	private int programId;
	private String programName;
	private Set<ProgramSub> programSubs = new HashSet<ProgramSub>(0);

	public Program() {
	}

	public Program(int programId, String programName) {
		this.programId = programId;
		this.programName = programName;
	}

	public Program(int programId, String programName,
			Set<ProgramSub> programSubs) {
		this.programId = programId;
		this.programName = programName;
		this.programSubs = programSubs;
	}

	public int getProgramId() {
		return this.programId;
	}

	public void setProgramId(int programId) {
		this.programId = programId;
	}

	public String getProgramName() {
		return this.programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

	public Set<ProgramSub> getProgramSubs() {
		return this.programSubs;
	}

	public void setProgramSubs(Set<ProgramSub> programSubs) {
		this.programSubs = programSubs;
	}

}
