package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 28, 2015 1:24:52 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProgramSub generated by hbm2java
 */
@Entity
@Table(name = "ProgramSub", catalog = "DSCARS")
public class ProgramSub implements java.io.Serializable {

	private Integer programSubId;
	private Program program;
	private int courseId;

	public ProgramSub() {
	}

	public ProgramSub(Program program, int courseId) {
		this.program = program;
		this.courseId = courseId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ProgramSubID", unique = true, nullable = false)
	public Integer getProgramSubId() {
		return this.programSubId;
	}

	public void setProgramSubId(Integer programSubId) {
		this.programSubId = programSubId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProgramID", nullable = false)
	public Program getProgram() {
		return this.program;
	}

	public void setProgram(Program program) {
		this.program = program;
	}

	@Column(name = "CourseID", nullable = false)
	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

}
