package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 28, 2015 1:24:52 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Program generated by hbm2java
 */
@Entity
@Table(name = "Program", catalog = "DSCARS")
public class Program implements java.io.Serializable {

	private int programId;
	private String programName;
	private Set<ProgramSub> programSubs = new HashSet<ProgramSub>(0);

	public Program() {
	}

	public Program(int programId, String programName) {
		this.programId = programId;
		this.programName = programName;
	}

	public Program(int programId, String programName,
			Set<ProgramSub> programSubs) {
		this.programId = programId;
		this.programName = programName;
		this.programSubs = programSubs;
	}

	@Id
	@Column(name = "ProgramID", unique = true, nullable = false)
	public int getProgramId() {
		return this.programId;
	}

	public void setProgramId(int programId) {
		this.programId = programId;
	}

	@Column(name = "ProgramName", nullable = false, length = 65535)
	public String getProgramName() {
		return this.programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "program")
	public Set<ProgramSub> getProgramSubs() {
		return this.programSubs;
	}

	public void setProgramSubs(Set<ProgramSub> programSubs) {
		this.programSubs = programSubs;
	}

}
