package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 28, 2015 1:24:52 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RecommendedSchedule generated by hbm2java
 */
@Entity
@Table(name = "RecommendedSchedule", catalog = "DSCARS")
public class RecommendedSchedule implements java.io.Serializable {

	private Integer recScheduleId;
	private User user;
	private Boolean isShadow;
	private Date runDateTime;
	private Set<RecommendedSection> recommendedSections = new HashSet<RecommendedSection>(
			0);

	public RecommendedSchedule() {
	}

	public RecommendedSchedule(User user, Date runDateTime) {
		this.user = user;
		this.runDateTime = runDateTime;
	}

	public RecommendedSchedule(User user, Boolean isShadow, Date runDateTime,
			Set<RecommendedSection> recommendedSections) {
		this.user = user;
		this.isShadow = isShadow;
		this.runDateTime = runDateTime;
		this.recommendedSections = recommendedSections;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RecScheduleID", unique = true, nullable = false)
	public Integer getRecScheduleId() {
		return this.recScheduleId;
	}

	public void setRecScheduleId(Integer recScheduleId) {
		this.recScheduleId = recScheduleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "IsShadow")
	public Boolean getIsShadow() {
		return this.isShadow;
	}

	public void setIsShadow(Boolean isShadow) {
		this.isShadow = isShadow;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RunDateTime", nullable = false, length = 19)
	public Date getRunDateTime() {
		return this.runDateTime;
	}

	public void setRunDateTime(Date runDateTime) {
		this.runDateTime = runDateTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recommendedSchedule")
	public Set<RecommendedSection> getRecommendedSections() {
		return this.recommendedSections;
	}

	public void setRecommendedSections(
			Set<RecommendedSection> recommendedSections) {
		this.recommendedSections = recommendedSections;
	}

}
