package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 27, 2015 4:54:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RecommendedSchedule generated by hbm2java
 */
public class RecommendedSchedule implements java.io.Serializable {

	private int recScheduleId;
	private User user;
	private Boolean isShadow;
	private Date runDateTime;
	private Set<RecommendedSection> recommendedSections = new HashSet<RecommendedSection>(
			0);

	public RecommendedSchedule() {
	}

	public RecommendedSchedule(int recScheduleId, User user, Date runDateTime) {
		this.recScheduleId = recScheduleId;
		this.user = user;
		this.runDateTime = runDateTime;
	}

	public RecommendedSchedule(int recScheduleId, User user, Boolean isShadow,
			Date runDateTime, Set<RecommendedSection> recommendedSections) {
		this.recScheduleId = recScheduleId;
		this.user = user;
		this.isShadow = isShadow;
		this.runDateTime = runDateTime;
		this.recommendedSections = recommendedSections;
	}

	public int getRecScheduleId() {
		return this.recScheduleId;
	}

	public void setRecScheduleId(int recScheduleId) {
		this.recScheduleId = recScheduleId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Boolean getIsShadow() {
		return this.isShadow;
	}

	public void setIsShadow(Boolean isShadow) {
		this.isShadow = isShadow;
	}

	public Date getRunDateTime() {
		return this.runDateTime;
	}

	public void setRunDateTime(Date runDateTime) {
		this.runDateTime = runDateTime;
	}

	public Set<RecommendedSection> getRecommendedSections() {
		return this.recommendedSections;
	}

	public void setRecommendedSections(
			Set<RecommendedSection> recommendedSections) {
		this.recommendedSections = recommendedSections;
	}

}
