package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 27, 2015 4:54:21 PM by Hibernate Tools 4.0.0

/**
 * RecommendedStudents generated by hbm2java
 */
public class RecommendedStudents implements java.io.Serializable {

	private int rsId;
	private Student student;
	private RecommendedSection recommendedSection;

	public RecommendedStudents() {
	}

	public RecommendedStudents(int rsId, Student student,
			RecommendedSection recommendedSection) {
		this.rsId = rsId;
		this.student = student;
		this.recommendedSection = recommendedSection;
	}

	public int getRsId() {
		return this.rsId;
	}

	public void setRsId(int rsId) {
		this.rsId = rsId;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public RecommendedSection getRecommendedSection() {
		return this.recommendedSection;
	}

	public void setRecommendedSection(RecommendedSection recommendedSection) {
		this.recommendedSection = recommendedSection;
	}

}
