package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 28, 2015 1:24:52 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RecommendedStudents generated by hbm2java
 */
@Entity
@Table(name = "RecommendedStudents", catalog = "DSCARS")
public class RecommendedStudents implements java.io.Serializable {

	private Integer rsId;
	private Student student;
	private RecommendedSection recommendedSection;

	public RecommendedStudents() {
	}

	public RecommendedStudents(Student student,
			RecommendedSection recommendedSection) {
		this.student = student;
		this.recommendedSection = recommendedSection;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RS_ID", unique = true, nullable = false)
	public Integer getRsId() {
		return this.rsId;
	}

	public void setRsId(Integer rsId) {
		this.rsId = rsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "StudentID", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RecSectionID", nullable = false)
	public RecommendedSection getRecommendedSection() {
		return this.recommendedSection;
	}

	public void setRecommendedSection(RecommendedSection recommendedSection) {
		this.recommendedSection = recommendedSection;
	}

}
