package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 27, 2015 4:54:21 PM by Hibernate Tools 4.0.0

/**
 * Requisite generated by hbm2java
 */
public class Requisite implements java.io.Serializable {

	private int requisiteId;
	private Course courseByPreReqCourseId;
	private Course courseByCourseId;

	public Requisite() {
	}

	public Requisite(int requisiteId, Course courseByPreReqCourseId,
			Course courseByCourseId) {
		this.requisiteId = requisiteId;
		this.courseByPreReqCourseId = courseByPreReqCourseId;
		this.courseByCourseId = courseByCourseId;
	}

	public int getRequisiteId() {
		return this.requisiteId;
	}

	public void setRequisiteId(int requisiteId) {
		this.requisiteId = requisiteId;
	}

	public Course getCourseByPreReqCourseId() {
		return this.courseByPreReqCourseId;
	}

	public void setCourseByPreReqCourseId(Course courseByPreReqCourseId) {
		this.courseByPreReqCourseId = courseByPreReqCourseId;
	}

	public Course getCourseByCourseId() {
		return this.courseByCourseId;
	}

	public void setCourseByCourseId(Course courseByCourseId) {
		this.courseByCourseId = courseByCourseId;
	}

}
