package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 27, 2015 4:54:21 PM by Hibernate Tools 4.0.0

/**
 * SectionTas generated by hbm2java
 */
public class SectionTas implements java.io.Serializable {

	private int staId;
	private int sectionId;
	private int instructorId;

	public SectionTas() {
	}

	public SectionTas(int staId, int sectionId, int instructorId) {
		this.staId = staId;
		this.sectionId = sectionId;
		this.instructorId = instructorId;
	}

	public int getStaId() {
		return this.staId;
	}

	public void setStaId(int staId) {
		this.staId = staId;
	}

	public int getSectionId() {
		return this.sectionId;
	}

	public void setSectionId(int sectionId) {
		this.sectionId = sectionId;
	}

	public int getInstructorId() {
		return this.instructorId;
	}

	public void setInstructorId(int instructorId) {
		this.instructorId = instructorId;
	}

}
