package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 27, 2015 4:54:21 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Section generated by hbm2java
 */
public class Section implements java.io.Serializable {

	private int sectionId;
	private Instructor instructor;
	private Course course;
	private User user;
	private int semesterId;
	private int maxClassSize;
	private int maxTas;
	private int courseDemand;
	private Date date;

	public Section() {
	}

	public Section(int sectionId, Instructor instructor, Course course,
			int semesterId, int maxClassSize, int maxTas, int courseDemand,
			Date date) {
		this.sectionId = sectionId;
		this.instructor = instructor;
		this.course = course;
		this.semesterId = semesterId;
		this.maxClassSize = maxClassSize;
		this.maxTas = maxTas;
		this.courseDemand = courseDemand;
		this.date = date;
	}

	public Section(int sectionId, Instructor instructor, Course course,
			User user, int semesterId, int maxClassSize, int maxTas,
			int courseDemand, Date date) {
		this.sectionId = sectionId;
		this.instructor = instructor;
		this.course = course;
		this.user = user;
		this.semesterId = semesterId;
		this.maxClassSize = maxClassSize;
		this.maxTas = maxTas;
		this.courseDemand = courseDemand;
		this.date = date;
	}

	public int getSectionId() {
		return this.sectionId;
	}

	public void setSectionId(int sectionId) {
		this.sectionId = sectionId;
	}

	public Instructor getInstructor() {
		return this.instructor;
	}

	public void setInstructor(Instructor instructor) {
		this.instructor = instructor;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getSemesterId() {
		return this.semesterId;
	}

	public void setSemesterId(int semesterId) {
		this.semesterId = semesterId;
	}

	public int getMaxClassSize() {
		return this.maxClassSize;
	}

	public void setMaxClassSize(int maxClassSize) {
		this.maxClassSize = maxClassSize;
	}

	public int getMaxTas() {
		return this.maxTas;
	}

	public void setMaxTas(int maxTas) {
		this.maxTas = maxTas;
	}

	public int getCourseDemand() {
		return this.courseDemand;
	}

	public void setCourseDemand(int courseDemand) {
		this.courseDemand = courseDemand;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
