package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 27, 2015 4:54:21 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private int studentId;
	private String name;
	private byte maxCoursesPerTerm;
	private Set<RecommendedStudents> recommendedStudentses = new HashSet<RecommendedStudents>(
			0);
	private Set<StudentCourseHistory> studentCourseHistories = new HashSet<StudentCourseHistory>(
			0);

	public Student() {
	}

	public Student(int studentId, String name, byte maxCoursesPerTerm) {
		this.studentId = studentId;
		this.name = name;
		this.maxCoursesPerTerm = maxCoursesPerTerm;
	}

	public Student(int studentId, String name, byte maxCoursesPerTerm,
			Set<RecommendedStudents> recommendedStudentses,
			Set<StudentCourseHistory> studentCourseHistories) {
		this.studentId = studentId;
		this.name = name;
		this.maxCoursesPerTerm = maxCoursesPerTerm;
		this.recommendedStudentses = recommendedStudentses;
		this.studentCourseHistories = studentCourseHistories;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte getMaxCoursesPerTerm() {
		return this.maxCoursesPerTerm;
	}

	public void setMaxCoursesPerTerm(byte maxCoursesPerTerm) {
		this.maxCoursesPerTerm = maxCoursesPerTerm;
	}

	public Set<RecommendedStudents> getRecommendedStudentses() {
		return this.recommendedStudentses;
	}

	public void setRecommendedStudentses(
			Set<RecommendedStudents> recommendedStudentses) {
		this.recommendedStudentses = recommendedStudentses;
	}

	public Set<StudentCourseHistory> getStudentCourseHistories() {
		return this.studentCourseHistories;
	}

	public void setStudentCourseHistories(
			Set<StudentCourseHistory> studentCourseHistories) {
		this.studentCourseHistories = studentCourseHistories;
	}

}
