package edu.gatech.omscs.dscars.test;
// default package
// Generated Mar 27, 2015 4:54:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int userId;
	private String userName;
	private String firstName;
	private String lastName;
	private String role;
	private String passwordHash;
	private Date lastLoginDate;
	private Set<CoreEngine> coreEngines = new HashSet<CoreEngine>(0);
	private Set<Section> sections = new HashSet<Section>(0);
	private Set<RecommendedSchedule> recommendedSchedules = new HashSet<RecommendedSchedule>(
			0);

	public User() {
	}

	public User(int userId, String userName, String role, String passwordHash) {
		this.userId = userId;
		this.userName = userName;
		this.role = role;
		this.passwordHash = passwordHash;
	}

	public User(int userId, String userName, String firstName, String lastName,
			String role, String passwordHash, Date lastLoginDate,
			Set<CoreEngine> coreEngines, Set<Section> sections,
			Set<RecommendedSchedule> recommendedSchedules) {
		this.userId = userId;
		this.userName = userName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.role = role;
		this.passwordHash = passwordHash;
		this.lastLoginDate = lastLoginDate;
		this.coreEngines = coreEngines;
		this.sections = sections;
		this.recommendedSchedules = recommendedSchedules;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getPasswordHash() {
		return this.passwordHash;
	}

	public void setPasswordHash(String passwordHash) {
		this.passwordHash = passwordHash;
	}

	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public Set<CoreEngine> getCoreEngines() {
		return this.coreEngines;
	}

	public void setCoreEngines(Set<CoreEngine> coreEngines) {
		this.coreEngines = coreEngines;
	}

	public Set<Section> getSections() {
		return this.sections;
	}

	public void setSections(Set<Section> sections) {
		this.sections = sections;
	}

	public Set<RecommendedSchedule> getRecommendedSchedules() {
		return this.recommendedSchedules;
	}

	public void setRecommendedSchedules(
			Set<RecommendedSchedule> recommendedSchedules) {
		this.recommendedSchedules = recommendedSchedules;
	}

}
